name: Github Actions Demo
on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs: 
  showInfo:
    runs-on: Ubuntu-latest
    steps:
      - run: |
          echo "${{github.action_repository}} triggered by ${{github.event_name}}"
          echo "Building branch ${{github.ref}}"
      - uses: actions/checkout@v4.1.1

      - name: List files
        run: |
          echo "The repo ${{github.repository}} contains the following"
          tree 
    

